import sys
import json
from datetime import datetime, timedelta
from pathlib import Path
from utils import get_worst_window 
from typing import List

class Analyzer:
    """
    This service consumes the data generated by Generator service and analyzes the logs and calculate metrics.
    """
    
    def __init__(self, file):
        self.file = Path(file)
        self.total_requests = 0
        self.failed_requests_4xx = 0
        self.failed_requests_5xx = 0
        self.slowest_endpoint = -sys.maxsize - 1
        self.slowest_endpoint_info = ''
        self.fastest_endpoint = sys.maxsize
        self.fastest_endpoint_info = ''
        self.busiest_endpoint = ''
        self.suspicious_ips = []
        self.windows = []
        self.error_rates_by_endpoints = {}
        
        
    def analyze_and_create_report(self) -> List:
        """
        This method streams the log file line by line finds and aggregates insights from the data.
        """
        with open(self.file) as file:
            endpoint_to_num_reqs = {}
            endpoint_to_errors = {}
            MAX_REQUESTS = 25
            window_size = timedelta(minutes=1)
            start_of_window = None
            ip_to_reqs = {}
            
            for line in file:
                self.total_requests += 1
                log = json.loads(line)
                log['timestamp'] = datetime.fromisoformat(log['timestamp'])
                ip = log['ip']
                ip_to_reqs[ip] = ip_to_reqs.get(ip, 0) + 1
                
                if self.total_requests == 1:
                    start_of_window = log['timestamp']
                
                # errors 
                method = log['method']
                endpoint = log['endpoint']         
                status_code = log['status_code']
                
                if status_code.startswith('4'):
                    self.failed_requests_4xx += 1
                    endpoint_to_errors[endpoint] = endpoint_to_errors.get(endpoint, 0) + 1  
                elif status_code.startswith('5'):
                    self.failed_requests_5xx += 1
                    endpoint_to_errors[endpoint] = endpoint_to_errors.get(endpoint, 0) + 1  
                    
                # number of reqs
                endpoint_to_num_reqs[endpoint] = endpoint_to_num_reqs.get(endpoint, 0) + 1      
                    
                # fastest and slowest endpoints
                response_time = log['response_time']
                
                if response_time > self.slowest_endpoint:
                    self.slowest_endpoint = response_time
                    self.slowest_endpoint_info = endpoint + " " + method + " ---> " + str(response_time) + "ms"
                
                if response_time < self.fastest_endpoint:
                    self.fastest_endpoint = response_time
                    self.fastest_endpoint_info = endpoint + " " + method + " ---> " + str(response_time) + "ms"
                
                # time window analysis
                end_of_window = log['timestamp']
                
                if end_of_window - start_of_window > window_size:
                    suspicious_ips_in_window = set()
                    for ip in ip_to_reqs:
                        if ip_to_reqs[ip] > MAX_REQUESTS:
                            self.suspicious_ips.append(ip)
                            suspicious_ips_in_window.add(ip)
                    # clear for a new window    
                    self.windows.append([f'{start_of_window} --> {end_of_window}', f'{self.total_requests}', f'{self.failed_requests_4xx}', f'{self.failed_requests_5xx}', f'{", ".join(suspicious_ips_in_window)}'])                        
                    ip_to_reqs.clear()
                    start_of_window = end_of_window 

            # aggregation of error rates
            for endpoint in endpoint_to_errors:   
                total_reqs_to_endpoint = endpoint_to_num_reqs[endpoint]
                errors_to_endpoint = endpoint_to_errors[endpoint]
                error_rate = round(errors_to_endpoint / total_reqs_to_endpoint, 3)
                self.error_rates_by_endpoints[endpoint] = error_rate
            
            # endpoint with the most requests
            self.busiest_endpoint = max(endpoint_to_num_reqs, key=endpoint_to_num_reqs.get) 
            self.busiest_endpoint += f" ---> {endpoint_to_num_reqs[self.busiest_endpoint]} requests"
            
            # report data
            return {
                "total_requests": self.total_requests,
                "total_failed_requests": self.failed_requests_4xx + self.failed_requests_5xx,
                "failed_requests_4xx": self.failed_requests_4xx,
                "failed_requests_5xx": self.failed_requests_5xx,
                "slowest_endpoint": self.slowest_endpoint,
                "slowest_endpoint_info": self.slowest_endpoint_info,
                "fastest_endpoint": self.fastest_endpoint,
                "fastest_endpoint_info": self.fastest_endpoint_info,
                "busiest_endpoint": self.busiest_endpoint,
                "worst_window": get_worst_window(self.windows),
                "suspicious_ips": self.suspicious_ips,
                "error_rates_by_endpoints": self.error_rates_by_endpoints,
            }